apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app-deployment
spec:
  selector:
    matchLabels:
      app: java-app
  replicas: 2
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
        - name: java-app
          # enter the path to your image, be sure to include the correct region prefix
          image: guy187/java-sample-app:98663f63fca9abf5a2388877cc73b5273853b7d0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 200m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: java-app-service
spec:
  type: NodePort
  selector:
    app: java-app
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
